pipeline {
    agent any
    
    stages {
        stage ("Pulling code"){
            steps {
                echo "Pulling the code from Github repo"
                git url:'https://github.com/manojgowda593/Jenkins-repo.git', branch: 'main'
            }
        }

        stage ("Build"){
            steps {
                echo "Building process"
                sh 'pip install bandit'
                sh 'python3 bandit -r .'
            }
        }

        stage ("Test") {
            steps {
                echo "Runnig test on code"
                sh 'python3 -m unittest discover tests/'
            }
        }

        stage ("check build") {
            steps {
                echo "Printing content of Jenkins folder"
                sh 'ls -l Jenkins/'
            }
        }
    }
}
